### PR TITLE
Updating dependencies

### PR DESCRIPTION
**Pull request by jthompson6**
-- Updating the dependencies for the Template project to version 0.9.6.
-- Adding the model modules
-- Marking the Alpine dependencies marked as provided (since Alpine already has them).

@codedeft @epahomov review?

### CODE REVIEW

**Comment by alpinebuilder** [comment]
Can you explain a little bit more, why dep should be provided?

**Comment by jthompson6** [comment]
Alpine already has them, so they shouldn't be packaged in the user's jar. Otherwise we will get the copy from the user's jar, and our copy, and it there could be confusion over which ones will be used. It also makes the user's jar about 10MB larger than necessary.

**Comment by epahomov** [comment]
LGTM

**Comment by epahomov** [comment]
previouse comment - it wasn't alpinebuilder, it was me))) Still was logged under him.

**Comment by jthompson6** [comment]
I guessed. It sounded like you.

**Pull request merged**
